### ISSUE TITLE
Restrict TWS Anomaly to time range 2002-09-01 to 2021-12-02

### ISSUE THREAD

**Issue by j08lue** [NASA-IMPACT/veda-data-pipelines#228]
Collection ID: `lis-tws-anomaly`

Fixing this issue fixes/closes #223, #210, and #192.

## Acceptance criteria
- [x] Set collection range to the above https://github.com/NASA-IMPACT/veda-data-pipelines/blob/74973e33ef6e03bfbbaeb515f66579065650dc72/data/collections/lis-tws-anomaly.json#L17-L18
- [x] Verified that all dates in the range exist (e.g. with something around `aws s3 ls s3://veda-data-store-staging/lis-tws-anomaly`, I assume)
- [x] Removed any orphaned assets from `veda-data-store-staging`
- [x] Closed #223 with a note
- [ ] Closed #210 with a note
- [x] Closed #192 with a note

**Comment by anayeaye** [comment]
@j08lue I agree adjusting the temporal range as you suggested + re-running the dashboard summaries function (`dashboard.update_collection_default_summaries(:collection_id)`) will correct the dashboard behavior and close #210 and #223.

I think we should still work issue #192 so that we will not have records pointing to invalid assets which might cause issues for someone creating a time series, for example.

**Comment by j08lue** [comment]
Ooops, please note: in the Dashboard, we use 2002-12-01, so we should probably keep that:

![image](https://user-images.githubusercontent.com/3404817/201208460-63368511-f674-476a-9585-29fd693c9edb.png)
https://www.earthdata.nasa.gov/dashboard/eis/datasets/tws-anomaly

**Comment by abarciauskas-bgse** [comment]
I started to look into this...

What I noticed:
* I reviewed the issue reported https://github.com/NASA-IMPACT/veda-data-pipelines/issues/223 - and I think the behavior is a bit different now, the first date is September 1, 2002 and the data is loading
![Screen Shot 2022-11-16 at 9 27 37 AM](https://user-images.githubusercontent.com/15016780/202250935-631d2415-d7d5-464c-b515-1320b97393d0.png)
* Looking at the metadata https://staging-stac.delta-backend.com/collections/lis-tws-anomaly, the temporal range is
```json
    "temporal": {
      "interval": [
        [
          "2002-08-31 18:00:00-06",
          "2021-11-30 17:00:00-07"
        ]
      ]
    }
```
* The summaries in the metadata is nearly the same:
```json
    "datetime": [
      "2002-09-01T00:00:00Z",
      "2021-12-01T00:00:00Z"
    ],
```
I think the difference between the temporal and summaries datetimes is at least partly due to use of timezone. It appears the temporal interval metadata is using mountain timezone? and the summaries metadata is using UTC.
* These dates matches what is currently represented in the dashboard as the start date

What I checked:
* the count of objects in S3 is about what we expect given the temporal range (i.e. there are 7031 days between date(2002, 9, 1) and date(2021, 12, 1) and 7033 files in the bucket and key.
* I checked that I was at least able to open each of the files https://github.com/NASA-IMPACT/veda-data-pipelines/blob/ab/check-tws-data/notebooks/check-tws-anamoly-data.ipynb (note that I have done the checking in 2 chunks (1170 files and then the rest) which is why this notebook output reports on 5860 items were checked.

Questions:
* Is it ok the summaries temporal interval is slightly different from the temporal interval metadata?
* Do we still want the start date to be 2002-12-01 or are we ok with 2002-08-31?
* Should we also check the min and max of each file? I can do this with the same script but it will run much slower and probably incur more cost.

cc @slesaad @j08lue

**Comment by abarciauskas-bgse** [comment]
I was able to update the collection temporal interval and summary. A few notes so I don't forget 😅 

* I ran into an error trying to run `poetry run insert-collection lis-tws-anomaly`
```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/aimeebarciauskas/miniconda3/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/Users/aimeebarciauskas/github/nasa-impact/veda-data-pipelines/scripts/collection.py", line 3, in <module>
    from pypgstac.load import Loader, Methods
  File "/Users/aimeebarciauskas/github/nasa-impact/veda-data-pipelines/venv/lib/python3.9/site-packages/pypgstac/load.py", line 24, in <module>
    import psycopg
  File "/Users/aimeebarciauskas/github/nasa-impact/veda-data-pipelines/venv/lib/python3.9/site-packages/psycopg/__init__.py", line 9, in <module>
    from . import pq  # noqa: F401 import early to stabilize side effects
  File "/Users/aimeebarciauskas/github/nasa-impact/veda-data-pipelines/venv/lib/python3.9/site-packages/psycopg/pq/__init__.py", line 114, in <module>
    import_from_libpq()
  File "/Users/aimeebarciauskas/github/nasa-impact/veda-data-pipelines/venv/lib/python3.9/site-packages/psycopg/pq/__init__.py", line 106, in import_from_libpq
    raise ImportError(
ImportError: no pq wrapper available.
Attempts made:
- couldn't import psycopg 'c' implementation: No module named 'psycopg_c'
- couldn't import psycopg 'binary' implementation: No module named 'psycopg_binary'
- couldn't import psycopg 'python' implementation: dlsym(0x7fcd7e807a30, PQsslInUse): symbol not found
```
which was resolved by installing `pip install psycopg-binary` - trying different things with venvs and updating poetry didn't work only running that install worked (for me)

* I add to export the (database secret) SECRET_NAME which is not in the README
* I had to connect to the database and run `SELECT dashboard.update_collection_default_summaries(:lis-tws-anomaly);`

**Comment by j08lue** [comment]
Great! Should we make some docs improvements based on your great feedback, @abarciauskas-bgse? ☝️ 

Regarding your questions @anayeaye:

> Is it ok the summaries temporal interval is slightly different from the temporal interval metadata?

Yes, no big deal, I think.

> Do we still want the start date to be 2002-12-01 or are we ok with 2002-08-31?

Anything that makes sense for the data - preserving as much of it as possible - is ok.

> Should we also check the min and max of each file? I can do this with the same script but it will run much slower and probably incur more cost.

Yes, I think the money is well spent reading all the data at least once during ingestion and checking that is sane. It potentially saves us a lot of manual work later and new ingests.

**Comment by anayeaye** [comment]
Sorry I didn't close up more issues after doing this in depth research and correction already [here](https://github.com/NASA-IMPACT/veda-data-pipelines/issues/192#issuecomment-1312837139)! 

However, I did not notice that the inbuilt collection extent functions we are adding a timezone when they should not. We are currently trying to [automate this extent calculation](https://github.com/NASA-IMPACT/veda-stac-ingestor/issues/25) in [veda-stac-ingestor](https://github.com/NASA-IMPACT/veda-stac-ingestor/blob/cc7448cf4309fb6bb6c6dee4ff3945ba34f7e367/api/src/vedaloader.py#L33-L50). I am going to update the backlog issue with additional acceptance criteria about this timezone mistake.
cc @abarciauskas-bgse @j08lue

**Comment by abarciauskas-bgse** [comment]
@j08lue @anayeaye I started to look at the acceptance criteria and I think it's all been covered but could you look and if you agree we can close this issue?

**Comment by anayeaye** [comment]
@abarciauskas-bgse I agree this is covered and good to close, I'm requesting QA in issue #210
