### ISSUE TITLE
Deploy MWAA to MCP production

### ISSUE THREAD

**Issue by amarouane-ABDELHAK** [NASA-IMPACT/veda-data-pipelines#332]
```[tasklist]
### Tasks
- [ ] https://github.com/NASA-IMPACT/veda-data-pipelines/issues/333
- [ ] https://github.com/NASA-IMPACT/veda-data-pipelines/issues/334
- [ ] https://github.com/NASA-IMPACT/veda-data-pipelines/issues/335
- [ ] https://github.com/NASA-IMPACT/veda-data-pipelines/issues/336
```
Using github actions along with OICD to deploy MWAA infrastructure into MCP

**Comment by gadomski** [comment]
@amarouane-ABDELHAK same question as in https://github.com/NASA-IMPACT/veda-data-pipelines/issues/335#issuecomment-1728237746, feels like this belongs in https://github.com/NASA-IMPACT/veda-data-airflow/ instead of here?

**Comment by gadomski** [comment]
Closing as complete as all tasks are done. Please re-open if this isn't the case.
